### ISSUE TITLE
Issues Blocks

### ISSUE THREAD

**Issue by txmodxoops** [bitcero/rmcommon#10] opened 2015-04-02 18:48 UTC
http://localhost/xoops-2.5.7rmcommon/htdocs/modules/rmcommon/blocks.php

Fatal error: Cannot unset string offsets in www\xoops-2.5.7rmcommon\htdocs\modules\rmcommon\class\template.php on line 410

Errors
Warning: array_merge(): Argument #2 is not an array in file /modules/rmcommon/class/template.php line 408

**Comment by bitcero** [comment] 2015-04-02 20:04
Which version of rmcommon and PHP are you using?

**Comment by txmodxoops** [comment] 2015-04-02 20:53
rmcommon version 2.2.8.8 updated via admin

php version 5.4.31

**Comment by bitcero** [comment] 2015-04-02 23:14
I always recommend to use the recent version of rmcommon (currently 2.2.9). Please check again for updates from "updates manager" in rmcommon.

The report that you are reporting does not match with recent version. Update to current version and if the problem persists let me know.

**Comment by txmodxoops** [comment] 2015-04-03 14:13
But in releases I see only 2.2.8.2

Now I can't do this, because the errors cause fatal stop

**Comment by bitcero** [comment] 2015-04-03 19:33
Please download https://github.com/bitcero/rmcommon/archive/master.zip and replace files. Remember to update the module directly on modules manager.

**Comment by txmodxoops** [comment] 2015-04-03 20:05
From debug Queries

0.000268 - SELECT dir FROM mod_rmcommon_plugins WHERE status=1
Error number: 1146
Error message: Table 'xoops257rmcommon.x899_mod_rmcommon_plugins' doesn't exist

**Comment by bitcero** [comment] 2015-04-05 05:59
You0ve found the error. It may have been an improper installation on the previous version. The plugins table has not been created. Please uninstall and install again the module.

**Comment by txmodxoops** [comment] 2015-04-05 08:46
I think you should put some controls for this plugin or anything.

If there are problems like mine, no one can get in admin.php

Fatal error: Call to a member function getInfo() on a non-object in www\xoops-2.5.7rmcommon\htdocs\modules\system\themes\redmexico\redmexico.php on line 17

I don't go into the database each time I have problems like this and uninstall the module.

**Comment by txmodxoops** [comment] 2015-04-05 09:20
Now it's ok

But I've problems to activate options in settings

**Comment by txmodxoops** [comment] 2015-04-05 09:32
There is a big bug

When I activate mod_rewrite in localhost, this create a link http://www.localhost/

**Comment by bitcero** [comment] 2015-04-05 20:30
First of all you must to understand that this problem is an isolated problem, and not a general problem, caused, probabily for a wrong instalation or a misconfiguration. This is the main reason why there is this tool to report errors. If it were a recurring problem then, you can be sure, that would already be solved.

In other side, remember that this is a voluntary work and I'm very interested to solve all bugs detected (although in fact not yet been established whether it is a bug, so research), so comments like "I don't go into the database each time I have problems like this and uninstall the module" are out of place. 

I suspect that this error is a problem on your configuration (system, xoops, or  something else) and I'm in the better disposition to help you to solve, but remember, it is an isolated issue. There are many other users using rmcommon and nobody report this issue until now. As I've said before, maybe you update the module files over a very old version or somehting else... this is what we need to discover.

Abotu the error "Fatal error: Call to a member function getInfo() on a non-object in www\xoops-2.5.7rmcommon\htdocs\modules\system\themes\redmexico\redmexico.php on line 17", there are a problem with rmcommon installation (check in xoops_modules_active file if rmcommon is in the list) because, once rmcommon is installed, admin.php ever will be displayed. Every time you goto to admin.php rmcommon will redirect to "modules/system/rmcommon". Then this problem is being caused for something else. Try to log directly into "modules/rmcommon" and check if the page is displaye or get an error of module inactive.

About htaccess... what module creates this link... and what is the information that you have about this big bug? If you have specfic information then I recommend you to open a new issue to solve this but remember to provide the minimal information to help to solve the problem: module, data writed in htaccess, process that you follow to generate this error, etc.

**Comment by txmodxoops** [comment] 2015-04-05 22:57
I wanted to point out that the problem getInfo(), is caused when in the folder theme  is the theme redmexico and isn't installed rmcommon. I wanted to suggest that, if possible, even if not installed and rmcommon redmexico theme is present, resolve with a script adapted.

"If rmcommon is not installed, redmexico theme does not work, please install this before."

I think this script without receiving fatal error

To the file .htaccess I did not understand how the error is generated.

On the root .htaccess file does not exist

**Comment by bitcero** [comment] 2015-04-06 00:00
> I wanted to point out that the problem getInfo(), is caused when in the folder theme is the theme redmexico and isn't installed rmcommon. I wanted to suggest that, if possible, even if not installed and rmcommon redmexico theme is present, resolve with a script adapted.

Well rmcommon includes all this, under normal operation. If the module files are simply deleted but some files left in XOOPS this kind of errors may happen. You must delete all files or uninstall module directly from modules manager. Please note that your case is not a "normal" circunstance and is impossible to prevent all the incredible circunstances under that any software will work. Another solution for this issue is to reconfigure **system** by selecting `default` gui theme from system preferences, but I think that, due to the nature of your problem, you can not see the preferences in XOOPS.

> To the file .htaccess I did not understand how the error is generated.
> On the root .htaccess file does not exist

Well, this is not a bug but a misconfiguration error. If the htacces does not exists, you can not use URL rewriting. **Remember**: when rmcommon or any other module for rmcommon is configured to use URL rewriting, then all URL must be formated according to configuration. Rmcommon only can do in your system those things that the syste, security allows trough Apache. If apache does not have the rigths to write files, then rmcommon will not write the apropiate rules in order to work with htaccess, then you need to add this rules manually (even create the htaccess file).

If you don't planning to use mod_Rewrite then change confgiuration settings. If you need to use rewriting then create the htaccess file (only works with Apache and compatible servers) first.

I will close this thread because the errors reported until now can be fixed trough configuration and independant from rmcommon code, and specific for your case. However, if you need to get help please open another Issue report and I'm very glad to help you.

**Closed by bitcero** 2015-04-06 00:00 UTC
